### PR TITLE
Fix code based on feedback

### LINKED ISSUE #178: Feedback for the collated code of A0148095X
- Put literals in a variable. <br> return "Todo list data load completed. Task list size: " 
- consider more conventional names. Perhaps also shorter, if possible. <br>
  notifySaveLocationChange instead of private void indicateChangeSaveLocationRequest(String location) { <br>
- Thats a mouthful! public void handleChangeSaveLocationRequestEvent(ChangeSaveLocationRequestEvent event) {  <br>
  Are you doing this to avoid a header comment! It has other side effects.
- Tests not written properly. Follow convention. One method per test case. We want to know what exactly failed when a build fails. Name test case according to the convention taught in the earlier tutorial.

### PR DESCRIPTION
**Pull request by INCENDE**
fixes #178

### CODE REVIEW

File: src/main/java/seedu/agendum/commons/events/model/SaveLocationChangeEvent.java [hunk 1]
```diff
@@ -0,0 +1,21 @@
+package seedu.agendum.commons.events.model;
+
+import seedu.agendum.commons.events.BaseEvent;
+//@@author A0148095X
+/** Indicates a request from model to change the save location of the data file*/
+public class SaveLocationChangeEvent extends BaseEvent {
```
Comment (rachx) [inline src/main/java/seedu/agendum/commons/events/model/SaveLocationChangeEvent.java]: change -> changed?

Comment (INCENDE) [reply src/main/java/seedu/agendum/commons/events/model/SaveLocationChangeEvent.java]: Actually it hasn't been changed yet haha

**Comment by INCENDE** [comment]
@rachx i renamed it to ChangeSaveLocation, is it better?

**Review by burnflare — APPROVED** [review]
